_target_: peft_models.vera.Vera
peft: Vera
vera_rank: 8
vera_dropout: 0.01
vera_target_modules: ['attn.q_proj', 'attn.k_proj', 'attn.v_proj', 'attn.proj', 'mlp.fc1_g', 'mlp.fc1_x', 'mlp.fc2']  # attn.q_proj, attn.k_proj, attn.v_proj, attn.proj, mlp.fc1_g, mlp.fc1_x, mlp.fc2