defaults:
  - _self_
  - env: local
  - model: timm
  - data: imagenet

log_dir: ${hydra:output_subdir}

hydra:
  output_subdir: ${exp_dir}/${data.module.name}/${make_group_name:${model.name},${model.finetune_method}}
  job:
    chdir: False
    env_set:
      HYDRA_FULL_ERROR: 1
  run:
    dir: .

override hydra/hydra_logging: disable
override hydra/job_logging: disable

seed: False

model:
  finetune_method: full
  optimizer: AdamW
  sam: False  # set trainer.precision=32 if you use sam
  adaptive_sam: False  # set trainer.precision=32 if you use sam
  lr: 0.00002
  nesterov: False
  scheduler: CosineAnneal
  T_max: ${trainer.max_epochs}
  warmstart: 2
  warmstart2: 0
  mixup: False
  mixup_alpha: 0.2
  weight_decay: 0.05 #5e-4
  undecay_norm: False
  label_smoothing: 0.0
  stochastic_depth: False
  resnet_dropout: 0.0
  squeeze_excitation: False
  apply_shakedrop: False
  zero_init_residual: False
  input_dim: 2
  input_channels: 3
  task: 'Classification'
  subtask: 'multiclass'  # 'multilabel'
  metric_computation_mode: 'epochwise'
  result_plot: null  # 'val' for validation plots (confusion matrix)
  num_classes: ${data.num_classes}
  metrics: ${metrics}
  epochs: ${trainer.max_epochs}
  name: ${model_name_extractor:${model._target_}}
  compile: False
  classification_head_dropout: 0.0
  token_aggregation_method: cls_token
  pretrained: False
    
data:
  module:
    random_batches: False  # sampling with replacement
    num_workers: 12
    prepare_data_per_node: False
    fold: null
  num_classes: ???
  cv:
    k: 1  # 1=no Cross Validation

metrics:
  - 'acc'
  - 'f1'

trainer:
  _target_: lightning.pytorch.Trainer
  callbacks: 
    progressbar:
      _target_: lightning.pytorch.callbacks.RichProgressBar
    lr_monitor:
      _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: epoch
    checkpoint:
      _target_: lightning.pytorch.callbacks.ModelCheckpoint
      dirpath: ???
      filename: '{epoch}-{val_loss:.2f}'
      auto_insert_metric_name: True
      save_last: True
  devices: 1
  accelerator: 'gpu'
  sync_batchnorm: False  # set to True if you use multiple GPUs
  enable_checkpointing: True
  max_epochs: 20
  benchmark: True
  deterministic: False
  precision: '16-mixed'
  enable_progress_bar: True
  strategy: 'ddp'
  logger:
    - _target_: lightning.pytorch.loggers.WandbLogger
      offline: False
      save_dir: ${log_dir}
    - _target_: lightning.pytorch.loggers.CSVLogger
      save_dir: ${log_dir}
      name: null
  num_sanity_val_steps: 0
  accumulate_grad_batches: 16
  #log_every_n_steps: 200
  # Some useful trainer parameters for debugging
  #limit_train_batches: 0.5
  #limit_val_batches: null
  #limit_test_batches: 0.25
  #gradient_clip_val: 0.5

precomputed_features:
  # num_cycles: 0
  precision: 32
  split: val #null
  compression: 4

wandb:
  entity: synergy_unit
  project: FM_adaptation_classification
  tags: null
  dir: ${log_dir}
  group: ${group_extractor:${log_dir}}
