# @package _global_
model:
  _target_: models.resenc_mil.ResEncoder_Classifier
  pretrained: True
  chpt_path: null
  classification_head_dropout: 0.2
  finetune_method: full
  token_aggregation_method: abmil
  cls_token_available: False
  use_mil_forward: True
  mil:
    batch_size: 2

trainer:
  strategy: 'ddp_find_unused_parameters_true'